# Site settings
name: 王永顺
location: 杭州
company: 上海汉得信息技术股份有限公司
position: Java软件工程师
github: https://github.com/ever-young/
phone: 166211*****
email: 2587336357@qq.com

baseurl: ""

avatarUrl: "https://images.alpgo.cc/images/avatar-asahiluna.png"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

